name: recipe_chatbot_app
description: A Flutter app that integrates a Gemini chatbot and Firebase for recipe suggestions based on user-provided ingredients.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^3.0.0
  http: ^0.13.3
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/